# Generated by Django 5.0.6 on 2024-06-16 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='content',
        ),
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='url',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song', to=settings.AUTH_USER_MODEL),
        ),
    ]
